In [32]:
import numpy as np
X=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
X.shape

(4, 3)

In [33]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X2D = pca.fit_transform(X)
X2D.shape

(4, 2)

In [38]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
X2D

array([[ 7.79422863,  0.        ],
       [ 2.59807621,  0.        ],
       [-2.59807621,  0.        ],
       [-7.79422863, -0.        ]])

In [40]:
X_recovered = pca.inverse_transform(X2D)
X_recovered

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])