In [1]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# Sample data
X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a FunctionTransformer using np.log function
transformer = FunctionTransformer(np.log, feature_names_out="one-to-one")

# Apply the transformation using transform()
X_transformed = transformer.transform(X)

print(X_transformed)


[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [4]:
np.log(2)

0.6931471805599453

In [11]:
#square funciton
def square(x):
    return x*2

In [12]:
transformer = FunctionTransformer(square, feature_names_out="one-to-one")

X_transformed = transformer.transform(X)

print(X_transformed)


[[ 2  4  6]
 [ 8 10 12]]
