In [2]:
# import numpy
import numpy as np

In [4]:
# create one dimensional array of hard coded values
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [31]:
# access array element by index
arr = np.array([1,2,3,4])
print(arr[0])

# modify array element 
arr[0] = 100
print(arr)

1
[100   2   3   4]


In [9]:
# create one dimensional array of values within the given range
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [13]:
# create a two dimensional array 
arr = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14]])

In [18]:
# create a two dimensional array with random numbers between 0 and 1
np.random.rand(3,4)

array([[0.30382141, 0.46471536, 0.11619559, 0.19795021],
       [0.92436647, 0.87635375, 0.09723231, 0.69274036],
       [0.34688857, 0.43689242, 0.60374348, 0.63606045]])

In [19]:
# create a two dimensional array with random numbers between 10 and 11
np.random.rand(3,4) + 10

array([[10.12788301, 10.7438313 , 10.40489251, 10.08876065],
       [10.67175302, 10.61925441, 10.59842178, 10.7067809 ],
       [10.3810884 , 10.39430522, 10.79904654, 10.4473923 ]])

In [23]:
# array reshaping, convert 1-D array to 2-D array
arr = np.array([1,2,3,4,5,6]).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# flatten a multi-dimensional array into 1-D array via ravel method
arr = np.arange(36).reshape(2,6,3)
arr.ravel()

# Cautions! : ravel method returns a flattened view of the original array, not a separate copy.
# Hence any update on it will update the original array.
# Rather use flatten method if you would need a complete separate copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [28]:
# flatten a multi-dimensional array into 1-D array via flatten method
arr = np.arange(36).reshape(2,6,3)
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
# arithematic operations on arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a % b  =", a % b)

a + b  = [ 6  8 10 12]
a - b  = [-4 -4 -4 -4]
a * b  = [ 5 12 21 32]
a / b  = [0.2        0.33333333 0.42857143 0.5       ]
a % b  = [1 2 3 4]


In [35]:
# conditional operatoin on arrays
arr = np.array([1,2,3,4,5,6])

# print true/false for each element for below condition
print(arr <=3)

# print only elements meeting below condition
print(arr[arr<=3])

[ True  True  True False False False]
[1 2 3]


In [36]:
# mathematical and statistical functions
arr = np.array([1,2,3,4,5,6])

for func in (arr.min, arr.max, arr.sum, arr.prod, arr.std, arr.var):
    print(func.__name__, "=", func())

min = 1
max = 6
sum = 21
prod = 720
std = 1.707825127659933
var = 2.9166666666666665


In [41]:
# sum across depth, heigh and width

arr = np.arange(24).reshape(2,3,4)
print(arr)

# sum across depth, axis=0
print(arr.sum(axis=0))


# sum across height, axis=1
print(arr.sum(axis=1))

# sum across width, axis=2
print(arr.sum(axis=2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [42]:
# universal functions
arr = np.array([1,2,3,4,5,6])

for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__, "=", func(arr))
    


 absolute = [1 2 3 4 5 6]

 sqrt = [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]

 exp = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]

 log = [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

 sign = [1 1 1 1 1 1]

 ceil = [1. 2. 3. 4. 5. 6.]

 modf = (array([0., 0., 0., 0., 0., 0.]), array([1., 2., 3., 4., 5., 6.]))

 isnan = [False False False False False False]

 cos = [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]


In [45]:
# binary functions
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

for func in (np.add, np.greater, np.maximum, np.minimum):
    print("\n", func.__name__, "=", func(arr1, arr2))


 add = [ 7  9 11 13 15]

 greater = [False False False False False]

 maximum = [ 6  7  8  9 10]

 minimum = [1 2 3 4 5]


In [54]:
# index range for 1-D arrays
arr = np.array([1,2,3,4,5])
print(arr[:3])   ## print elements from index 0 to (3-1)
print(arr[1:3])  ## print elements from index 1 to (3-1)
print(arr[1:-1]) ## print elements from index 1 to (last index -1)

[1 2 3]
[2 3]
[2 3 4]
[1 4]


In [57]:
# iterate over array
arr = np.arange(10).reshape(2,5)
for i in arr:
    print(i)

# iterate over each individual elements of the array
for i in arr.flat:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [60]:
# stacking together different arrays
q1 = np.array([1,2,3])
q2 = np.array([4,5,6])
q3 = np.array([7,8,9])

# vertical stacking
q4 = np.vstack((q1, q2, q3))
print(q4)

# horizontal stacking
q5 = np.hstack((q1, q2, q3))
print(q5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [66]:
# split arrays
arr = np.arange(24).reshape(4,6)
print(arr)

# vertical split
v1,v2 = np.vsplit(arr, 2)
print(v1)
print(v2)

# horizontal split
v3,v4 = np.hsplit(arr,2)
print(v3)
print(v4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [68]:
# matrix operations : Transpose

m = np.arange(24).reshape(4,6)

print("Original matrix:")
print(m)

print("After transpose:")
print(m.T)


Original matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
After transpose:
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [69]:
# matrix operations : Multiplication
m1=np.array([[1,2],[3,4],[5,6]])
print(m1)

m2=np.array([[7,8,9],[10,11,12]])
print(m2)

M = m1.dot(m2)
print(M)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [73]:
# matrix operations : Inverse
import numpy.linalg as linalg
m = np.array([[1,2,3],[5,7,11],[21,29,31]])
print(linalg.inv(m))

[[-2.31818182  0.56818182  0.02272727]
 [ 1.72727273 -0.72727273  0.09090909]
 [-0.04545455  0.29545455 -0.06818182]]


In [72]:
# identity matrix
import numpy.linalg as linalg
m = np.array([[1,2,3],[5,7,11],[21,29,31]])
print(m.dot(linalg.inv(m))) ## this generates identity matrix as we multiply a matrix by its inverse

[[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [-2.98372438e-16  1.00000000e+00 -5.55111512e-17]
 [ 5.78009862e-15  1.27675648e-15  1.00000000e+00]]


## Solving a linear equation
* $2x + 6y = 6$
* $5x + 3y = -9$

In [75]:
a  = np.array([[2, 6], [5, 3]])
b = np.array([6, -9])
s = linalg.solve(a, b)
s

array([-3.,  2.])